config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post '/signin' => 'application#signin'
  get '/signout' => 'application#signout'
  get '/search' => 'home#search', as: 'search'
  resources :post_categories

  resources :categories

  resources :posts do
  	  resources :comments
  	  resources :favorites
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :post_categories
  has_many :favorites
  has_many :categories, through: :post_categories
  has_many :favorited_by, class_name: 'User', through: :favorites
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  validates_presence_of :title
  validates_presence_of :body
  validates_presence_of :photo
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find_by(id: params[:id])
    @fav_count = Favorite.where("post_id = #{@post.id}").count
    @user = @post.user
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.comments.destroy_all
    @post.favorites.destroy_all
    @post.categories.destroy_all
    @post.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :photo, :user_id, :name, category_ids:[])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :title, id: :post_title, placeholder: 'Title' %>
  </div>

  <div class="field">
      <%= form.text_area :body, id: :post_body, placeholder: "What's Cooking?" %>
  </div>

  <div class="field" id="photo">
    <%= form.label :photo %>
    <%= form.file_field :photo, id: :post_photo %>
  </div>

  <div class="field">
    <%= form.label :categories %>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
    <div class="collection-check-box">
    <%= b.check_box %>
    <%= b.label %>
    </div>
  <% end %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, :value => @current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div id="posts">
<h1>Editing Post</h1>
<div id="form">
<%= render 'form', post: @post %>
</div>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/new.html.erb
<div id="posts">
<h1>New Post</h1>
<div id="form">
<%= render 'form', post: @post %>
</div>
</div>

app/views/posts/show.html.erb
<div id="posts">
<p id="notice"><%= notice %></p>
<% if @current_user && @user == @current_user %>
<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Delete Post', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<h2>
  <%= @post.title %>
</h2>
<p>by <%= link_to @user.username, @user %> on <%= @post.created_at.strftime("%D at %I:%M %p") %></p>
<p id="categories">posted under:
<% @post.categories.each do |category| %>
<%= link_to category.name, category %>
<% end %>
</p>
<% if @current_user %>
<div id="favorite">
<%= render 'favorites/form', favorite: Favorite.new %>
</div>
<% end %>
<div id="favorite">
<p id="fav_count"> This post has been liked <%= @fav_count %> times!</p>
</div>
<% if @post.photo.url != '/images/original/missing.png' %>
<div id="postimage" style="background-image: url('<%= @post.photo.url %>');">
</div>
<% end %>

<p id="body">
  <%= @post.body.html_safe %>
</p>
<div id="comments_section">
<% @post.comments.each do |comment| %>
<p class="comment"><span class="comment_user"><%=link_to comment.user.username, comment.user %>:</span> <span class="comment_body"><%= comment.body %></span></p>
<p><%= comment.created_at.strftime("%D at %I:%M %p") %>
<% if comment.user == @current_user %>
<%= link_to 'Delete Comment', post_comment_path(@post, comment), method: :delete %>
<% end %>
<% end %>
<% if @current_user %>
<%= render 'comments/form', comment: Comment.new %>
<% end %>
</div>
</div>